services:
  web:
    container_name: web
    build: web
    ports:
      - '3030:3030'
    volumes:
      - ./web/:/web/
      - /web/node_modules/
  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./app/:/app/
      - /app/instance/
