[package]
name = "sedaro-nano-queries"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.22.0", features = ["lexer"] }
serde = { version = "1.0.195", features = ["derive", "rc"] }
serde_json = "1.0.108"

[build-dependencies]
lalrpop = "0.22.0"