name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose up --build -d
    - name: Docker Login
      run: aws ecr get-login-password | docker login --username AWS --password-stdin 624507112707.dkr.ecr.us-east-1.amazonaws.com
    - name: Push Docker image to AWS ECR
      run: docker compose push
